using System.Collections.ObjectModel;

namespace Chat.Server;

/// <summary>
/// Owns the server-run attachment directory and its byte quota. File names
/// supplied by clients are metadata only; every on-disk name is generated by
/// this class from a cryptographically random attachment id.
/// </summary>
internal sealed class AttachmentStore : IAsyncDisposable
{
    private const int MaxAttachmentRecords = 1024;
    private readonly object _gate = new();
    private readonly string _rootDirectory;
    private readonly long _maxBytes;
    private readonly Dictionary<string, StoredAttachment> _attachments = new(StringComparer.Ordinal);
    private long _reservedBytes;
    private int _disposed;

    public AttachmentStore(long maxBytes)
    {
        if (maxBytes <= 0)
            throw new ArgumentOutOfRangeException(nameof(maxBytes));

        _maxBytes = maxBytes;
        _rootDirectory = Path.Combine(
            Path.GetTempPath(),
            "Lab1Chat",
            $"server-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_rootDirectory);
    }

    public bool TryReserve(
        string fileName,
        long fileSize,
        bool isImage,
        out UploadReservation? reservation,
        out string error)
    {
        reservation = null;
        error = string.Empty;

        lock (_gate)
        {
            if (Volatile.Read(ref _disposed) != 0)
            {
                error = "Kho tệp của máy chủ đã đóng.";
                return false;
            }

            if (fileSize < 0)
            {
                error = "Kích thước tệp không hợp lệ.";
                return false;
            }

            if (fileSize > _maxBytes - _reservedBytes)
            {
                error = "Kho tệp của máy chủ đã đầy.";
                return false;
            }

            if (_attachments.Count >= MaxAttachmentRecords)
            {
                error = "Kho tệp của máy chủ đã đạt giới hạn số lượng tệp.";
                return false;
            }

            if (fileSize > 0)
            {
                try
                {
                    var root = Path.GetPathRoot(_rootDirectory);
                    if (root is not null
                        && new DriveInfo(root).AvailableFreeSpace < fileSize + _reservedBytes)
                    {
                        error = "Dung lượng đĩa của máy chủ không đủ.";
                        return false;
                    }
                }
                catch (IOException)
                {
                    // Some virtual/containerized file systems do not expose
                    // DriveInfo; the logical quota still protects the store.
                }
                catch (UnauthorizedAccessException)
                {
                    // The actual FileStream operation remains authoritative.
                }
            }

            var id = Guid.NewGuid().ToString("N");
            var temporaryPath = Path.Combine(_rootDirectory, $"{id}.upload");
            var finalPath = Path.Combine(_rootDirectory, $"{id}.bin");
            _reservedBytes += fileSize;
            reservation = new UploadReservation(
                id,
                fileName,
                fileSize,
                isImage,
                temporaryPath,
                finalPath);
            return true;
        }
    }

    public StoredAttachment Commit(UploadReservation reservation, string sha256)
    {
        ArgumentNullException.ThrowIfNull(reservation);
        ArgumentException.ThrowIfNullOrEmpty(sha256);

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);
            if (reservation.State != UploadReservationState.Reserved)
                throw new InvalidOperationException("Reservation không còn hiệu lực.");

            File.Move(reservation.TemporaryPath, reservation.FinalPath);
            var attachment = new StoredAttachment(
                reservation.AttachmentId,
                reservation.FileName,
                reservation.FileSize,
                sha256,
                reservation.IsImage,
                reservation.FinalPath);
            _attachments.Add(attachment.AttachmentId, attachment);
            reservation.State = UploadReservationState.Committed;
            return attachment;
        }
    }

    public bool TryGet(string attachmentId, out StoredAttachment? attachment)
    {
        attachment = null;
        if (string.IsNullOrWhiteSpace(attachmentId))
            return false;

        lock (_gate)
            return _attachments.TryGetValue(attachmentId, out attachment);
    }

    public void Release(UploadReservation reservation)
    {
        ArgumentNullException.ThrowIfNull(reservation);

        string? temporaryPath = null;
        lock (_gate)
        {
            if (reservation.State != UploadReservationState.Reserved)
                return;

            reservation.State = UploadReservationState.Released;
            _reservedBytes -= reservation.FileSize;
            temporaryPath = reservation.TemporaryPath;
        }

        TryDelete(temporaryPath);
    }

    public void Remove(string attachmentId)
    {
        StoredAttachment? attachment;
        lock (_gate)
        {
            if (!_attachments.Remove(attachmentId, out attachment))
                return;
            _reservedBytes -= attachment.FileSize;
        }

        TryDelete(attachment.FilePath);
    }

    public ValueTask DisposeAsync()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
            return ValueTask.CompletedTask;

        ReadOnlyCollection<string> paths;
        lock (_gate)
        {
            paths = _attachments.Values
                .Select(static attachment => attachment.FilePath)
                .ToList()
                .AsReadOnly();
            _attachments.Clear();
            _reservedBytes = 0;
        }

        // The store is disposed after transfer handlers stop, so a single
        // recursive delete is safe and also removes incomplete .upload files.
        try
        {
            if (Directory.Exists(_rootDirectory))
                Directory.Delete(_rootDirectory, recursive: true);
        }
        catch (IOException)
        {
            foreach (var path in paths)
                TryDelete(path);
            TryDeleteDirectory(_rootDirectory);
        }
        catch (UnauthorizedAccessException)
        {
            foreach (var path in paths)
                TryDelete(path);
            TryDeleteDirectory(_rootDirectory);
        }

        return ValueTask.CompletedTask;
    }

    private static void TryDelete(string? path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return;

        try
        {
            if (File.Exists(path))
                File.Delete(path);
        }
        catch (IOException)
        {
            // Cleanup is best effort during process shutdown.
        }
        catch (UnauthorizedAccessException)
        {
            // Cleanup is best effort during process shutdown.
        }
    }

    private static void TryDeleteDirectory(string path)
    {
        try
        {
            if (Directory.Exists(path))
                Directory.Delete(path, recursive: true);
        }
        catch (IOException)
        {
            // Cleanup is best effort during process shutdown.
        }
        catch (UnauthorizedAccessException)
        {
            // Cleanup is best effort during process shutdown.
        }
    }
}

internal sealed class UploadReservation
{
    public UploadReservation(
        string attachmentId,
        string fileName,
        long fileSize,
        bool isImage,
        string temporaryPath,
        string finalPath)
    {
        AttachmentId = attachmentId;
        FileName = fileName;
        FileSize = fileSize;
        IsImage = isImage;
        TemporaryPath = temporaryPath;
        FinalPath = finalPath;
    }

    public string AttachmentId { get; }
    public string FileName { get; }
    public long FileSize { get; }
    public bool IsImage { get; }
    public string TemporaryPath { get; }
    public string FinalPath { get; }
    public UploadReservationState State { get; set; }
}

internal enum UploadReservationState
{
    Reserved,
    Committed,
    Released
}

internal sealed record StoredAttachment(
    string AttachmentId,
    string FileName,
    long FileSize,
    string Sha256,
    bool IsImage,
    string FilePath);
