<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Lab1Chat.Client</AssemblyName>
    <RootNamespace>Chat.Client</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Chat.Shared\Chat.Shared.csproj" />
    <EmbeddedResource Include="Assets\Twemoji\*.png" />
    <None Update="Assets\Twemoji\LICENSE-GRAPHICS" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Assets\Twemoji\TWEMOJI-NOTICE.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
